LET fname = "JOHN"
LET SENDER = "MARY"
PRINT "DEAR " + fname + ","
PRINT "I HOPE THIS LETTER FINDS YOU WELL."
PRINT "I AM WRITING TO SHARE SOME WONDERFUL NEWS."
PRINT "I HAVE BEEN PROMOTED AT WORK!"
PRINT "I WANTED TO SHARE THIS JOY WITH YOU."
PRINT "BEST REGARDS,"
PRINT SENDER